---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at <https://ds202-at-isu.github.io/labs.html> for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed. Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

**Step 12.3:**

This is a line form RStudio Karrigan: Went as expected

This is a line from RStudio Cael L: Step 12.3 went smoothly, and I was able to get the github repository to load into RStudio successfully.

**Step 12.4:**

Cael L. Step 12.4: The main problem I was having with committing changes to github it would set back the version of the READ.ME file in RStudio and it wouldn't allow me to enter visual mode. I was able to fix this problem by deleting any information that RStudio didn't know and it allowed me to commit messages.

This line is from RStudio Quita: Went as expected

**Step 12.5:**

Cael L: My main issue in trying to push my changes to Github. I kept running into merge errors and running into errors with the remote package. I was able to solve this problem by making sure to pull of the changes made to the repository before trying to push my changes, and I also decide to uninstall the remote package and I was able to push my changes much more smoothly.

**Step 12.6:**

Cael L: There wasn't any issue with the changes I made to the RMarkdown file not showing up in GitHub. Sometimes it would take 2 commits or pushes to get the changes to load, but other than that it went really smooth.
